### PR TITLE
hpsjam: Beautify and added credit to Nils.

### PR DESCRIPTION
**Pull request by iFriendGit**

### CODE REVIEW

**Comment by hselasky** [comment]
You should use the full name here. And ":" after hpsjam in the commit message.

**Comment by iFriendGit** [comment]
full name you mean Nils's? If so, I don't know it, sorry.

**Comment by hselasky** [comment]
Does Nils have a GitHub account?

**Comment by iFriendGit** [comment]
i think yes, but also dont know it

**Comment by hselasky** [comment]
Let's try to ask him first.

**Comment by hselasky** [comment]
Sent him an e-mail.

**Comment by MirracleZ** [comment]
[he does](https://github.com/dingodoppelt)
;)

**Comment by iFriendGit** [comment]
Great, Nils! Can we add your real full name though to the credits? If so, what is it pls?

**Comment by iFriendGit** [comment]
ahhhh, though it was Nils, but it's you Missy, sorry!

**Comment by MirracleZ** [comment]
haha ja :P 
saw loads of messages in my email so had to check it out. I'm sure he'll reply soon enough himself!

**Comment by iFriendGit** [comment]
@dingodoppelt

**Comment by hselasky** [comment]
Submitted manually. Thanks!

**Pull request closed without merging**
