### PR TITLE
Update help.h

### PR DESCRIPTION
**Pull request by iFriendGit**
hpsjam. Update text in help.h

### CODE REVIEW

**Comment by hselasky** [comment]
Patch looks good.

Can you cleanup the commit message?

Just write:
hpsjam. Update text in help.h

And I'll merge it!

Thank you!

**Comment by hselasky** [comment]
And also if possible use (signed off by):
git commit --amend -s

**Comment by iFriendGit** [comment]
atm I'm not using cli git, only online (learing, so will not be able to do "git commit --amend -s"), sorry

**Comment by hselasky** [comment]
No problem. I'll fix.

**Comment by hselasky** [comment]
Merged manually.

**Pull request closed without merging**
